[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2

# optional: reverb/websocket process - sesuaikan commandnya
[program:reverb]
command=php artisan reverb:start
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
autorestart=true

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=3600
